name: diffuscene
channels:
  - conda-forge
  - pytorch
  - defaults
  - nvidia
dependencies:
  - cython
  - numpy
  - networkx
  - pyrr
  - pyyaml
  - python=3.11
  - cuda-toolkit=12.8.0
  #- pytorch=1.13.0 # to be updated
  #- torchvision=0.14.0 # to be updated
  - pillow
  - scipy
  - tqdm
  - matplotlib
  - wxpython
  - pip:
    - trimesh
    - simple_3dviz
    #- pytorch-fast-transformers==0.4.0 #outdated
    - num2words
    - nltk
    - einops_exts
    - kornia
    - rotary_embedding_torch
    - transformers
    - clip
    - pyvista
    #- torchtext #outdated
    - seaborn
    - wandb
    - torchvision
